name: instagram_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.5
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.1.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  provider: ^6.0.3
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/ic_instagram.svg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
